language: python
env:
    - DJANGO_VERSION=1.11.3
    - DJANGO_VERSION=1.10.7
    - DJANGO_VERSION=1.8.18
python:
  - "2.7"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
install:
  - "pip install -r dev-requirements.txt"
  - "pip install sendgrid"
  - "pip install django==$DJANGO_VERSION"
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then nosetests -c nose.cfg -I test_post_to_sendgrid; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then nosetests -c nose.cfg; fi'
  - flake8 sendgrid_backend/
